    - name: apt update 
      apt: 
        update_cache: yes 
      when: ansible_facts["os_family"]=="Debian"

    - name: install apache 
      apt: 
        name: nginx
        state: present
    - name: create dir  
      file: 
        path: "{{ dir_name }}"
        state: directory
    
    - name: 
      command: "ls {{ dir_name }}"
      register: results 
    - name: print stdout
      debug:
        var: results.stdout
    - name: copy template
      template:
        src: myconfig
        dest: myconfig
      notify: restart nginx

    - name: Create users
      user:
       name: "{{ item }}"
       state: present
      with_items:
        - ansible
        - ansible-1
        - ansible-2
        - ansible-3
        - ansible-4